parameters:

services:
    elasticsearch.client_builder:
        class: Elasticsearch\ClientBuilder
        factory: [Elasticsearch\ClientBuilder, create]
        calls:
            - [setHosts, [[%elasticsearch_host%]]]

    elasticsearch_client:
        class: Elasticsearch\Client
        factory: [@elasticsearch.client_builder, build]
        lazy: true

    simple_property_serializer:
        class: League\Tactician\Logger\PropertySerializer\SimplePropertySerializer

    class_property_formatter:
        class: League\Tactician\Logger\Formatter\ClassPropertiesFormatter
        arguments:
            - @simple_property_serializer

    tactician.middleware.logger:
        class: League\Tactician\Logger\LoggerMiddleware
        arguments:
            - @class_property_formatter
            - @logger

    create_elasticsearch_index_command:
        class: AppBundle\Command\CreateElasticsearchIndexCommand
        arguments:
            - @elasticsearch_client
        tags:
            - { name: console.command }